'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Animation_Game.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property alert_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alert_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alert_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alert_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alert_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alert_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alert_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alert_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alert_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alert_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Blue_Teleporter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue Teleporter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cave_Entrance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cave Entrance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Coin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Coin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fly_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fly_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fly_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fly_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Green_Teleporter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green Teleporter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heal_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heal_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heal_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heal_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heal_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heal_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ImmortalHD_s_Face() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImmortalHD's Face", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jump_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jump_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_S() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.S", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_Space() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.Space", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_W() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key.W", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ladder_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ladder_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ladder_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ladder_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_1_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 1 Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_2_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 2 Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_3_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 3 Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_4_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 4 Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_5_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 5 Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Level_6_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Level 6 Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lever() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lever", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lever0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lever0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lever1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lever1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Main_Menu_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Main Menu Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prone_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prone_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property proneStab_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proneStab_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property proneStab_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proneStab_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Red_Teleporter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red Teleporter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rope_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rope_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rope_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rope_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot2_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoot2_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoot2_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shootF_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shootF_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shootF_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shootF_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shootF_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shootF_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sit_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sit_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabO1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabO1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabO1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabO1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabO2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabO2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabO2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabO2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabOF_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabOF_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabOF_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabOF_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabOF_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabOF_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabT1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabT1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabT1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabT1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabT1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabT1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabT2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabT2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabT2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabT2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabT2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabT2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabTF_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabTF_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabTF_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabTF_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabTF_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabTF_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stabTF_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stabTF_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand1_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand1_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand2_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stand2_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stand2_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO3_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO3_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO3_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingO3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingO3_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingOF_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingOF_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingOF_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingOF_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingOF_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingOF_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingOF_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingOF_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingP1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingP1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingP1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingP1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingP1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingP1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingP2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingP2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingP2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingP2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingP2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingP2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingPF_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingPF_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingPF_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingPF_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingPF_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingPF_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingPF_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingPF_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT3_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT3_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT3_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingT3_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingT3_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingTF_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingTF_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingTF_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingTF_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingTF_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingTF_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property swingTF_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("swingTF_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Blue11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Blue11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Green1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Green1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Green11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Green11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Red1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Red1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Red11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Red11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Yellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Yellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property teleporter_Yellow11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("teleporter_Yellow11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk2_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk2_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk2_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk2_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walk2_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walk2_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Yellow_Teleporter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yellow Teleporter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
